package org.onelab.data.meta;

import java.lang.reflect.Field;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * ID描述对象
 * @author Chunliang.Han on 15/8/15.
 */
public class IDMeta {

  /**
   * entity的ID
   */
  private Field idField;

  /**
   * ID对应的类
   */
  private Column idColumn;

  /**
   * ID生成策略
   */
  private GeneratedValue generatedValue;

  public IDMeta(Field idField, Column idColumn, GeneratedValue generatedValue) {
    this.idField = idField;
    this.idColumn = idColumn;
    this.generatedValue = generatedValue;
  }

  /**
   * 是否由数据库自动生成ID
   */
  public boolean isAutoGeneratedValue(){
    return generatedValue != null && generatedValue.strategy() == GenerationType.AUTO;
  }

  public Field getIdField() {
    return idField;
  }

  public Column getIdColumn() {
    return idColumn;
  }

  public GeneratedValue getGeneratedValue() {
    return generatedValue;
  }
}
